### ISSUE TITLE
can't find .dll

### ISSUE THREAD

**Issue by Falinere** [Aida-Enna/MognetPlugin#15]
I've downloaded every zip folder I can find, none of them have MognetPlugin.dll to put into ACT. What am I missing?

**Comment by Boroak** [comment]
HI Falinere,

I found it at the bottom of 

https://github.com/Aida-Enna/MognetPlugin/releases/tag/v0.3.0

**Comment by Aida-Enna** [comment]
Sorry, this was an issue with the Wiki linking to the wrong repo and has since been fixed.
