### ISSUE TITLE
option to display your character's name instead of YOU

### ISSUE THREAD

**Issue by SelfAfflicted** [Aida-Enna/MognetPlugin#17]
A suggestion rather, would it be possible to Add a text box in the plugin options to replace YOU with character's name?

**Comment by Aida-Enna** [comment]
This is controlled by ACT and configurable via the instructions below:

https://github.com/Aida-Enna/MognetPlugin/wiki/How-to-change-the-default-%22YOU%22-character-name-and-make-the-bot-print-your-real-one
