### ISSUE TITLE
The bot is offline

### ISSUE THREAD

**Issue by enternius** [Aida-Enna/MognetPlugin#19]
Not sure if this is the place to bring it up, but for the better part of a week, the bot has been offline. I'm curious if there's any intention to fix it, as there doesn't seem to be any other similar bot anywhere that does what this one does.

**Comment by Aida-Enna** [comment]
Sorry, I must have missed the email notification from this! The bot is back online and should be functioning as normal. Please comment to confirm this for me, thank you!
