### ISSUE TITLE
Project health and server code

### ISSUE THREAD

**Issue by rftr** [Aida-Enna/MognetPlugin#20]
Bot is offline last few days and no updates on any past issues. 
Can we have an update about the plugin continuity There's nothing quite like it and i really wish we could use it again. 

If @Aida-Enna or @castanhob aren't willing to continue, which is absolutely understandable, there are any plans on opening the server code?

**Comment by Aida-Enna** [comment]
Oh wow, I must have missed the email about the bot from the previous issue. Lemme go take a look right now, sorry!

**Comment by Aida-Enna** [comment]
All fixed, the bot should be back online now :+1: Please comment to confirm that it's working on your side, thank you!

**Comment by enternius** [comment]
Works great for me, thanks a ton.
