### ISSUE TITLE
The bot failed again

### ISSUE THREAD

**Issue by enternius** [Aida-Enna/MognetPlugin#21]
Sorry to have to trouble you again, maybe it was the most recent update, but the bot died again.

**Comment by rftr** [comment]
bot is still offline

**Comment by Aida-Enna** [comment]
For some reason this repo -really- doesn't seem to want to notify me when issues are opened, even though I've turned on all notifications for it. Someone poked me on discord and I restarted it. I'll have one of my other bots keep an eye on it and restart it whenever it goes down. Sorry for the problem!

**Comment by Aida-Enna** [comment]
Fixed in #22
